// Generated by CoffeeScript 1.9.1
(function() {
  var SI1145, si1145;

  SI1145 = require('../../lib/adafruit-si1145');

  si1145 = new SI1145();

  si1145.readUV(function(err, res) {
    console.log(res);
    console.log(err);
    return true;
  });

}).call(this);
